export enum RequiredOnPage {
    ANYWHERE_IN_DOCUMENT = "ANYWHERE_IN_DOCUMENT",
    ON_FIRST_PAGE = "ON_FIRST_PAGE",
    ON_LAST_PAGE = "ON_LAST_PAGE",
    NOT_REQUIRED = "NOT_REQUIRED",
    PROHIBITED = "PROHIBITED",
    IN_RANGE_OF_PAGES = "IN_RANGE_OF_PAGES"
  }
  