export enum SearchElementType {
    CASCADE_GROUP_SEARCH_ELEMENT = "CASCADE_GROUP_SEARCH_ELEMENT",
    CHECK_BOX_GROUP_SEARCH_ELEMENT = "CHECK_BOX_GROUP_SEARCH_ELEMENT",
    REPEATABLE_GROUP_SEARCH_ELEMENT = "REPEATABLE_GROUP_SEARCH_ELEMENT",
    SIMPLE_GROUP_SEARCH_ELEMENT = "SIMPLE_GROUP_SEARCH_ELEMENT",
    DESIGNER_KEY_VALUE_PAIR_SEARCH_ELEMENT = "DESIGNER_KEY_VALUE_PAIR_SEARCH_ELEMENT",
  
    AMOUNT_TEXT_SEARCH_ELEMENT = "AMOUNT_TEXT_SEARCH_ELEMENT",
    BARCODE_SEARCH_ELEMENT = "BARCODE_SEARCH_ELEMENT",
    DATE_TEXT_SEARCH_ELEMENT = "DATE_TEXT_SEARCH_ELEMENT",
    HORIZONTAL_COLOR_SEPARATOR_SEARCH_ELEMENT = "HORIZONTAL_COLOR_SEPARATOR_SEARCH_ELEMENT",
    IMAGE_SEARCH_ELEMENT = "IMAGE_SEARCH_ELEMENT",
    LABEL_TEXT_SEARCH_ELEMENT = "LABEL_TEXT_SEARCH_ELEMENT",
    LINE_SEPARATOR_SEARCH_ELEMENT = "LINE_SEPARATOR_SEARCH_ELEMENT",
    REG_EX_TEXT_SEARCH_ELEMENT = "REG_EX_TEXT_SEARCH_ELEMENT",
    PARAGRAPH_SEARCH_ELEMENT = "PARAGRAPH_SEARCH_ELEMENT",
    RECTANGLE_SEARCH_ELEMENT = "RECTANGLE_SEARCH_ELEMENT",
    TERM_TEXT_SEARCH_ELEMENT = "TERM_TEXT_SEARCH_ELEMENT",
    VERTICAL_COLOR_SEPARATOR_SEARCH_ELEMENT = "VERTICAL_COLOR_SEPARATOR_SEARCH_ELEMENT",
    WHITE_GAP_SEARCH_ELEMENT = "WHITE_GAP_SEARCH_ELEMENT",
    SIGNATURE_SEARCH_ELEMENT = "SIGNATURE_SEARCH_ELEMENT",
    READ_ALL_TEXT_SEARCH_ELEMENT = "READ_ALL_TEXT_SEARCH_ELEMENT",
    TEMPLATE_SEARCH_ELEMENT = "TEMPLATE_SEARCH_ELEMENT",
    ALPHABET_SEARCH_ELEMENT = "ALPHABET_SEARCH_ELEMENT",
  
    KEY_VALUE_PAIR_SEARCH_ELEMENT = "KEY_VALUE_PAIR_SEARCH_ELEMENT",
  
    TERMS_SEQUENCE_TEXT_SEARCH_ELEMENT = "TERMS_SEQUENCE_TEXT_SEARCH_ELEMENT",
    REGEXES_SEQUENCE_TEXT_SEARCH_ELEMENT = "REGEXES_SEQUENCE_TEXT_SEARCH_ELEMENT"
  }
  